name: CI for Django App

on:
  push:
    branches: [main, testing]
  pull_request:
    branches: [main, testing]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Python Packages
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright
          playwright install

      - name: Apply Database Migrations
        working-directory: ./ledgerpay
        run: python manage.py migrate

      - name: Execute Tests with Coverage
        working-directory: ./ledgerpay
        run: |
          python manage.py runserver &
          sleep 7
          pytest --cov=payments --cov-report=xml

      - name: Submit Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: tests
          name: django-ci-report
